alias update='apt-get update; apt-get -y --allow-unauthenticated upgrade; apt-get -y --allow-unauthenticated dist-upgrade;updategits'
alias searchport='netstat -lanp | grep -i '
alias without='grep -iv '
alias updategits='cd / && find . -name ".git" -type d | sed "s/\/.git//" | xargs -P10 -I{} git -C {} pull | grep -vi "already up-to-date"'
alias wig='python3 ~/wig/wig.py'
alias pydictor='python3 ~/pydictor/pydictor.py'
alias dir='ls -la'
alias myip='echo My IP: ; curl http://ipecho.net/plain'
alias mitm='bettercap -I eth0 --random-mac -D --full-duplex -X -P '*' --httpd'
alias pipin='pip install -r requirements.txt'
alias adit='nano ~/.bash_aliases'

