alias update='apt-get update; apt-get -y upgrade; apt-get -y dist-upgrade;updategits'
alias searchport='netstat -lanp | grep -i '
alias without='grep -iv '
alias updategits='cd / && find . -name ".git" -type d 2>/dev/null | sed "s/\/.git//" | xargs -P10 -I{} git -C {} pull | grep -vi "already up-to-date"'
alias dir='ls -la'
alias myip='echo My IP: $(curl http://ipecho.net/plain)'
alias pipin='pip install -r requirements.txt'
alias adit='CD=$(pwd); cd ~ && nano .bash_aliases && source .bash_aliases && cd $CD && echo Aliasses updated!'
alias explorer='nautilus 2>1 1>/dev/null &'
